version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "5008:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "13307:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
      - ./docker/db/mysql_data:/var/lib/mysql
    env_file:
      - ./docker/db/db-variables.env

  test_db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "13308:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
      - ./docker/db/test_mysql_data:/var/lib/mysql
    env_file:
      - ./docker/db/test_db-variables.env
